### PR TITLE
re-do for version 2

### PR DESCRIPTION
**Pull request by ahdinosaur**
feedbacks pls @pietgeursen @mixmix @iainkirkpatrick @yoshuawuyts :)

full-stack app using `inux`: [holodex/app#compost](https://github.com/holodex/app/tree/compost), see `dex/**/app.js`

### CODE REVIEW

**Comment by ahdinosaur** [comment]
if this goes well, i'm considering moving this sweetened API into `inu` and migrating the current `inu.start` into a separate `inu-engine` or something.

**Comment by yoshuawuyts** [comment]
I like how inu works - not too big of a fan of `redux` personally as it passes around a whole lot of extra objects and stuff which creates a bit of a bumpy API I find

**Comment by ahdinosaur** [comment]
hey @yoshuawuyts, with this re-write the `inux` API is more similar to `choo` than `redux`, although i did get a few ideas for implementation details from my favorite `redux` modules. soo... not sure what you mean with regards to `inux`, can you elaborate?

**Comment by ahdinosaur** [comment]
merged because why not, feedback still welcome. :)

**Comment by yoshuawuyts** [comment]
:D yay!

**Pull request merged**
